name: 📦

on:
  push:
    branches:
      - "**"

jobs:
  python-package:
    name: Make PyPI package
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux_2_28_x86_64
    steps:
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/checkout@v3
      - name: Install LAPACK, OpenBLAS
        run:
          yum install -y lapack-devel blas-devel opensll-devel

      - name: Install maturin
        run: python3 -m pip install "maturin>=1.7" auditwheel
      - name: Build python package
        run: |
          maturin build
          auditwheel repair target/wheels/ndelement-0.1.0.dev0-py3-none-manylinux_2_35_x86_64.whl
      - name: Show
        run: |
          auditwheel show target/wheels/ndelement-0.1.0.dev0-py3-none-manylinux_2_35_x86_64.whl
